export const PERMISSIONS = [
  "dashboard.view",
  "profile.view",
  "profile.edit",
  "notification.view",
  "user.view",
  "user.create",
  "user.edit",
  "user.delete",
  "user.enable-disable",
  "user.assign-role",
  "role.view",
  "role.create",
  "role.edit",
  "role.delete",
  "department.view",
  "department.create",
  "department.edit",
  "department.delete",
  "department.member.view",
  "project.view",
  "project.create",
  "project.edit",
  "project.delete",
  "project.member.view",
  "project.member.add",
  "project.member.remove",
  "skill.submit",
  "skill.submission.view",
  "skill.review",
  "skill.publish",
  "skill.rate",
  "skill.rating.view",
  "skill.rating.manage",
  "skill.library.view",
  "skill.download",
  "skill.download-history.view",
  "skill-category.view",
  "skill-category.edit",
  "skill-category.enable-disable",
  "skill-category.sort",
  "login-log.view",
  "operation-log.view",
  "log.export",
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number];

interface PermissionMeta {
  module: string;
  name: string;
}

export const PERMISSION_META: Record<PermissionCode, PermissionMeta> = {
  "dashboard.view": { module: "首页", name: "查看首页" },
  "profile.view": { module: "个人信息", name: "查看个人信息" },
  "profile.edit": { module: "个人信息", name: "修改个人信息" },
  "notification.view": { module: "通知中心", name: "查看通知" },
  "user.view": { module: "用户管理", name: "查看用户" },
  "user.create": { module: "用户管理", name: "创建用户" },
  "user.edit": { module: "用户管理", name: "编辑用户" },
  "user.delete": { module: "用户管理", name: "删除用户" },
  "user.enable-disable": { module: "用户管理", name: "启停用用户" },
  "user.assign-role": { module: "用户管理", name: "分配用户角色" },
  "role.view": { module: "角色管理", name: "查看角色" },
  "role.create": { module: "角色管理", name: "创建角色" },
  "role.edit": { module: "角色管理", name: "编辑角色" },
  "role.delete": { module: "角色管理", name: "删除角色" },
  "department.view": { module: "部门管理", name: "查看部门" },
  "department.create": { module: "部门管理", name: "创建部门" },
  "department.edit": { module: "部门管理", name: "编辑部门" },
  "department.delete": { module: "部门管理", name: "删除部门" },
  "department.member.view": { module: "部门管理", name: "查看部门成员" },
  "project.view": { module: "项目管理", name: "查看项目" },
  "project.create": { module: "项目管理", name: "创建项目" },
  "project.edit": { module: "项目管理", name: "编辑项目" },
  "project.delete": { module: "项目管理", name: "删除项目" },
  "project.member.view": { module: "项目管理", name: "查看项目成员" },
  "project.member.add": { module: "项目管理", name: "添加项目成员" },
  "project.member.remove": { module: "项目管理", name: "移除项目成员" },
  "skill.submit": { module: "Skill 管理", name: "提交 Skill" },
  "skill.submission.view": { module: "Skill 管理", name: "查看提审记录" },
  "skill.review": { module: "Skill 管理", name: "审核 Skill" },
  "skill.publish": { module: "Skill 管理", name: "发布 Skill" },
  "skill.rate": { module: "Skill 管理", name: "评价 Skill" },
  "skill.rating.view": { module: "Skill 管理", name: "查看评价记录" },
  "skill.rating.manage": { module: "Skill 管理", name: "管理评价记录" },
  "skill.library.view": { module: "Skill 管理", name: "查看 Skill 库" },
  "skill.download": { module: "Skill 管理", name: "下载 Skill 包" },
  "skill.download-history.view": { module: "Skill 管理", name: "查看下载记录" },
  "skill-category.view": { module: "Skill 分类", name: "查看 Skill 分类" },
  "skill-category.edit": { module: "Skill 分类", name: "编辑 Skill 分类" },
  "skill-category.enable-disable": { module: "Skill 分类", name: "启停用 Skill 分类" },
  "skill-category.sort": { module: "Skill 分类", name: "调整 Skill 分类排序" },
  "login-log.view": { module: "日志管理", name: "查看登录日志" },
  "operation-log.view": { module: "日志管理", name: "查看操作日志" },
  "log.export": { module: "日志管理", name: "导出日志" },
};

export function getPermissionMeta(permissionCode: PermissionCode): PermissionMeta {
  return PERMISSION_META[permissionCode];
}

export const SYSTEM_CATEGORIES = [
  "AI智能",
  "开发工具",
  "效率提升",
  "数据分析",
  "内容创作",
  "安全合规",
  "通讯协作",
] as const;
